### ISSUE TITLE
Bugs in MzIdentML validator

### ISSUE THREAD

**Issue by UKQIDA** [HUPO-PSI/mzIdentML#93] opened 2017-09-06 14:30 UTC
[55merge_omssa.mzid.zip](https://github.com/HUPO-PSI/mzIdentML/files/1281429/55merge_omssa.mzid.zip)
@germa 

Hi Gerhard,

When I used MzIdentML validator to valid the attached file, I got the following messages. It seems that the only error message is a bug which isn't true about the file. Could you have a look at the issues please? I was using mzIdentMLValidator_GUI_v1.4.26-SNAPSHOT.

The following messages were obtained during the validation of your XML file:

Message 1:
    Rule ID: PeptideModification_must_rule
    Level: ERROR
    Context(Flaw in the rule definition: PeptideModification_must_rule )
    --> Could not find property 'Modification' of the xpath expression '/Modification/cvParam/@accession' (element position: 1) in the given object of: uk.ac.ebi.jmzidml.model.mzidml.Peptide - Did you mean 'modification' ?

Message 2:
    Rule ID: ProteinAmbiguityGroup_may_rule
    Level: INFO
    Context(/MzIdentML/DataCollection/AnalysisData/ProteinDetectionList/proteinAmbiguityGroup/cvParam/@accession )
    --> The term 'protein ambiguity group result details' (MS:1001147) doesn't have children in the ontology 'MS', yet the CvMapping recommends to use them. The CvTerm will be removed.

Message 3:
    Rule ID: SpectrumIdentificationList_may_rule
    Level: INFO
    Context(/cvParam/@accession ) in 2 locations
    --> None of the given CvTerms were found at '/MzIdentML/DataCollection/AnalysisData/SpectrumIdentificationList/cvParam/@accession' because no values were found:
  - Any children term of MS:1001184 (search statistics). The term can be repeated. The matching value has to be the identifier of the term, not its name.

Message 4:
    Rule ID: SearchDatabase_may_rule
    Level: INFO
    Context(/searchDatabase/cvParam/@accession ) in 2 locations
    --> None of the given CvTerms were found at '/MzIdentML/DataCollection/Inputs/searchDatabase/cvParam/@accession' because no values were found:
  - Any children term of MS:1001011 (search database details). The term can be repeated. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1000561 (data file checksum type). The term can be repeated. The matching value has to be the identifier of the term, not its name.

Message 5:
    Rule ID: SourceFile_may_rule
    Level: INFO
    Context(/sourceFile/cvParam/@accession ) in 2 locations
    --> None of the given CvTerms were found at '/MzIdentML/DataCollection/Inputs/sourceFile/cvParam/@accession' because no values were found:
  - Any children term of MS:1000561 (data file checksum type). The term can be repeated. The matching value has to be the identifier of the term, not its name.

Message 6:
    Rule ID: SearchDatabaseDatabaseName_may_rule
    Level: INFO
    Context(/searchDatabase/databaseName/cvParam/@accession ) in 2 locations
    --> None of the given CvTerms were found at '/MzIdentML/DataCollection/Inputs/searchDatabase/databaseName/cvParam/@accession' because no values were found:
  - Any children term of MS:1001013 (database name). The term can be repeated. The matching value has to be the identifier of the term, not its name.

======== RULE STATISTICS ========
Invalid XML schema validation: 0

CvMappingRule total count: 40
CvMappingRules not run: 6
CvMappingRules run & invalid: 6
CvMappingRules invalid XPath: 1
CvMappingRules run & valid: 28

ObjectRules total count: 1
ObjectRules not run: 0
ObjectRules run & not matching: 0
ObjectRules run & valid: 1

Unanticipated CV terms: 0
Not matching messages received: 6

**Comment by germa** [comment] 2018-09-11 14:10
It seems like the Flaw error
    Context(Flaw in the rule definition: PeptideModification_must_rule )
is caused by the used validator-2.0.9.jar library

**Comment by germa** [comment] 2018-09-13 13:55
Fixed in mzIdentMLValidator_GUI_v1.4.31-SNAPSHOT

**Closed by germa** 2018-09-13 13:55 UTC
