### ISSUE TITLE
Provide an OWL version xlmod?

### ISSUE THREAD

**Issue by matentzn** [HUPO-PSI/mzIdentML#117] opened 2020-12-22 19:10 UTC
Hey all!

I am trying to process all ontologies in the OBO foundry at the moment, and I have a problem with xlmod because no owl version is provided. If I helped you to provide one, would you mind adding it to the xlmod cv release file directory?

All best!

**Comment by matentzn** [comment] 2021-03-05 11:42
Hello again!

According to the [OBO foundry policies](http://obofoundry.org/principles/fp-002-format.html):

> However, the official OWL PURL for the ontology must resolve to a syntactically valid OWL file using the RDF-XML syntax.

Would it be possible to provide this, or do you consider xlmod inactive now?

**Comment by cmungall** [comment] 2021-03-09 17:18
Note that xlmod.obo cannot be translated to OWL as there are syntax errors:

```
Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@75e91545
    Stack trace:
LINENO: 860 - expected newline or end of line but found: xsd:string  
LINE: property_value: base specificities: "(Guanine)" xsd:string        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:60)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1254)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1208)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1165)
        org.obolibrary.robot.IOHelper.loadOntology(IOHelper.java:531)
        org.obolibrary.robot.IOHelper.loadOntology(IOHelper.java:417)
        org.obolibrary.robot.IOHelper.loadOntology(IOHelper.java:298)
        org.obolibrary.robot.CommandLineHelper.getInputOntology(CommandLineHelper.java:487)
        org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:585)
LINENO: 860 - expected newline or end of line but found: xsd:string  
LINE: property_value: base specificities: "(Guanine)" xsd:string        org.obolibrary.oboformat.parser.OBOFormatParser.error(OBOFormatParser.java:1465)
        org.obolibrary.oboformat.parser.OBOFormatParser.forceParseNlOrEof(OBOFormatParser.java:1303)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseEOL(OBOFormatParser.java:1271)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseTermFrameClauseEOL(OBOFormatParser.java:599)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseTermFrame(OBOFormatParser.java:572)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseEntityFrame(OBOFormatParser.java:539)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseOBODoc(OBOFormatParser.java:349)
        org.obolibrary.oboformat.parser.OBOFormatParser.parse(OBOFormatParser.java:307)
        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:79)
        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:58)
```

The issue is caused by xlmod making properties with spaces in the ID

**Comment by pmt706** [comment] 2021-03-23 19:37
Hi All,

I'm happy to fix the errors in this that are causing issues in OWL generation, but can I suggest that we move the home of XLMOD to somewhere that isn't hidden within mzIdentML's github ?

Paul

**Comment by cmungall** [comment] 2021-03-23 19:40
Yes, I think it's a good idea for each ontology to have its own distinct repo.

I recommend creating a new repo using https://github.com/INCATools/ontology-development-kit/ -- if you are comfortable running python scripts OR docker this should be easy, but we can help if not.

**Comment by edeutsch** [comment] 2021-03-23 20:29
I agree that we should put it in its own repo.

I would suggest something like XLMOD-CV to be similar to our other CVs

Left to our own devices, I would have modeled the repo on this: https://github.com/HUPO-PSI/psi-mod-CV

But we could try the ODK stuff suggested above by Chris if Paul is up for it. If that seems too complicated then modeling on psi-mod-CV seems adequate to me.

**Comment by matentzn** [comment] 2021-09-07 09:13
Hey all, are there any updates on xlmod CV? Is there a new repo / OWL product available we can register at the OBO foundry pages?

**Comment by matentzn** [comment] 2022-02-01 18:03
Sorry to be a massive pain, but xlmod is the last remaining ontology that cannot be processed at all by the [OBO Dashboard](http://dashboard.obofoundry.org/dashboard/index.html).

![image](https://user-images.githubusercontent.com/7070631/152024986-bf6503a5-5524-4321-a92e-7a4befd4bcf3.png)
 

Are their any plans to fix this? Or do you prefer to label xlmod as `inactive` on OBO foundry?

**Comment by matentzn** [comment] 2022-02-02 09:34
Awesome :) Thanks @edeutsch !

**Comment by edeutsch** [comment] 2022-02-06 03:47
The new repo is here:
https://github.com/HUPO-PSI/xlmod-CV

Please switch to using the contents there. And post an issue there if you have any further trouble.

**Comment by matentzn** [comment] 2022-02-07 09:35
That is great.

- [ ] Please update this file: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/xlmod.yml

by fixing the `products` row (add a .owl artefact and fix all/any other URLs in that config file - this is the file that is responsible for your PURLs).

Please assign me as a reviewer as well and link to this issue.

- [ ] Please update this file: https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/xlmod.md

Again, add the .owl product (always lower case, no matter if your raw file is upper case), and review the entire metadata record for any changes you may want to apply, including changing the tracker, adding to the description etc. Assign me as a reviewer and link to this issue here.

Thank you @edeutsch I will look forward to having all of OBO Foundry parsable soon :)

**Comment by matentzn** [comment] 2022-02-10 13:09
Great, the purl has now been[merged](https://github.com/OBOFoundry/purl.obolibrary.org/pull/822). Now the last part, updating the Metadata (see comment above). After that is done, I am out of your hair, @edeutsch :) Thank you!

**Comment by matentzn** [comment] 2022-02-18 08:23
Beautiful, all done @edeutsch thank you very much for your help getting this all cleaned up!

**Comment by edeutsch** [comment] 2022-02-18 18:09
thank you for nudging us to get it done. closing.

**Closed by edeutsch** 2022-02-18 18:09 UTC
