### ISSUE TITLE
can't launch the validator

### ISSUE THREAD

**Issue by prvst** [HUPO-PSI/mzIdentML#111] opened 2019-05-22 14:08 UTC
Hi,

I need some assistance with the mzID validator. I'm trying to run it on Linux.

command:
`java -Xms2048m -jar mzIdentMLValidator-1.4.34-SNAPSHOT.jar`

error:
`Error: Unable to initialize main class psidev.psi.pi.validator.MzIdentMLValidatorGUI`

**Comment by andrewrobertjones** [comment] 2019-07-02 15:00
@germa  Gerhard, would you mind responding to this one?

**Comment by germa** [comment] 2019-07-02 15:08
If you use Java 8, please try:
java -Xms2048m -cp .\lib -jar mzIdentMLValidator-1.4.34-SNAPSHOT.jar

For Java 9, 10, 11 try
java -Xms2048m --add-modules java.xml.bind -cp .\lib -jar mzIdentMLValidator-1.4.34-SNAPSHOT.jar

**Comment by prvst** [comment] 2019-07-09 13:41
I have Java 11:
```
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

I tried his:
`java -Xms2048m --add-modules java.xml.bind -cp .\lib -jar mzIdentMLValidator-1.4.34-SNAPSHOT.jar`

and got this:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

**Comment by germa** [comment] 2019-07-16 11:23
Sorry, my mistake. The old version mzIdentMLValidator-1.4.34-SNAPSHOT.jar ran only with Java 9 and 10.

I compiled now a new version, which runs with Java 11 and 12:
java -Xms2048m -cp .\lib -jar .\mzIdentMLValidator-1.4.35-SNAPSHOT.jar

You can start it with run.bat after you adapted the variable JAVA_HOME pointing to your Java installation.

**Comment by prvst** [comment] 2019-07-25 13:49
Got a different error now, same JDK as I described above:

```
Error: LinkageError occurred while loading main class psidev.psi.pi.validator.MzIdentMLValidatorGUI
java.lang.UnsupportedClassVersionError: psidev/psi/pi/validator/MzIdentMLValidatorGUI has been
compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java
Runtime only recognizes class file versions up to 55.0
```

**Comment by germa** [comment] 2019-08-13 12:54
I think the problem is that you the old Java 11, see https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers
Please try again with Java 12, e.g. from https://jdk.java.net/12/ or https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html

**Comment by prvst** [comment] 2020-01-22 14:40
sorry for the long delay. We have Java 11 (openjdk version "11.0.5" 2019-10-15) on our systems, I would like to avoid changing that. I'm still having issues with the validator:

```
> java -Xms2048m --add-modules java.xml.bind -cp .\lib -jar mzIdentMLValidator-1.4.35-SNAPSHOT.jar`
Error occurred during initialization of boot layer. java.lang.module.FindException: Module java.xml.bind not found
```

I did some [digging](https://stackoverflow.com/a/52502208) and apparently java.xml.bind is deprecated since Java 9 and was removed from Java 11. The link contains a fix for the issue as well.

**Comment by germa** [comment] 2020-01-22 14:55
@Felipe: can you please try without --add-modules java.xml.bind :
java -Xms2048m -cp .\lib -jar mzIdentMLValidator-1.4.35-SNAPSHOT.jar

**Comment by nicorellius** [comment] 2020-02-26 20:23
I'm seeing the same problem here... Validator version 1.4.35 failing to launch on Ubuntu 18.04, Java 11.0.6:

Setting JAR as executable and running:

`java -jar mzIdentMLValidator-1.4.35-SNAPSHOT.jar`

fails with the following error:

    Error: LinkageError occurred while loading main class
    psidev.psi.pi.validator.MzIdentMLValidatorGUI
    java.lang.UnsupportedClassVersionError: psidev/psi/pi/validator/MzIdentMLValidatorGUI
    has been compiled by a more recent version of the Java Runtime (class file version
    56.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Running `run.sh` also fails:

`Error: Unable to access jarfile mzIdentMLValidator-1.4.35-SNAPSHOT.jar`

Permissions are correct and I can run other JARs no problem. Any ideas what is going on?

I've tried most of the things in this issue already except Java 12. Is this the fix? If so, I'd suggest not claiming to support Java 11 in repo README, as this is the default version for Ubuntu 18.04 using the package manager (and everyone on Ubuntu will try this first).

**Comment by nicorellius** [comment] 2020-02-26 20:37
Installed Java 13 with the following:

    sudo apt -y update
    sudo add-apt-repository ppa:linuxuprising/java
    sudo apt -y update
    sudo apt -y install oracle-java13-installer

Then downloaded [validator ZIP](https://github.com/HUPO-PSI/mzIdentML/raw/master/validator/mzIdentMLValidator_GUI_v1.4.35-SNAPSHOT.zip), unpacked it, then ran the following command (from this thread above):

`java -Xms2048m -cp .\lib -jar mzIdentMLValidator-1.4.35-SNAPSHOT.jar`

and the GUI launched and I'm validating an mzIdentML file.

**Comment by ypriverol** [comment] 2022-10-07 10:46
In the new implementation https://github.com/ypriverol/mzidentml-validator all dependencies are packaged within the same tool jar. I will close this issue unless someone has major complains and wants to open it again.

**Closed by ypriverol** 2022-10-07 10:46 UTC
